### ISSUE TITLE
uWSGI не отвечает на некоторые запросы при дефолтной конфигурации

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#167]
Развернул свежую версию ngw с uWSGI.

Запускаю сервер, открываю админку, и нажимаю несколько раз F5 в браузере - в некоторых случаях от сервера нет ответа, после следующего обновления - страница появляется. Работа в админке невозможна, поскольку во многих случаях сервер не получает данные из браузера при создании новых слоёв. 
Так же рисуется только один из нескольких тайлов. 
Через pserve этого не наблюдается.

Конфиг
```
development.ini                                                                                                                                                         484/484               100%
[app:main]
use = egg:nextgisweb

# .... . ......... ................. .....
config = %(here)s/config.ini

# .... . ................. ..... .......... logging
# logging = %(here)s/logging.ini

# ........ ... ....... .........
# pyramid.reload_templates = true
# pyramid.includes = pyramid_debugtoolbar

[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = 6543

[uwsgi]
module = nextgisweb.uwsgiapp
env = PASTE_CONFIG=%p

socket =  :6543
protocol = http

workers = 2
threads = 4
```

Лог в терминале:
```
/home/zadmin/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:471: SAWarning: Unicode type received non-unicode bind param value.
  processors[key](compiled_params[key])
[pid: 6518|app: 0|req: 1/1] 192.168.2.123 () {34 vars in 780 bytes} [Thu May 22 16:26:05 2014] GET /resource/3 => generated 12463 bytes in 85 msecs (HTTP/1.1 200) 2 headers in 82 bytes (2 switches on core 0)
[pid: 6518|app: 0|req: 2/2] 192.168.2.123 () {38 vars in 908 bytes} [Thu May 22 16:26:05 2014] GET /static/b73d683fe014fe015f50a47ca9390431/amd/dojo/dojo.js => generated 0 bytes in 7 msecs (HTTP/1.1 304) 3 headers in 144 bytes (0 switches on core 2)
[pid: 6518|app: 0|req: 3/3] 192.168.2.123 () {34 vars in 780 bytes} [Thu May 22 16:26:08 2014] GET /resource/3 => generated 12463 bytes in 27 msecs (HTTP/1.1 200) 2 headers in 82 bytes (2 switches on core 3)
[pid: 6518|app: 0|req: 6/4] 192.168.2.123 () {38 vars in 933 bytes} [Thu May 22 16:26:08 2014] GET /static/b73d683fe014fe015f50a47ca9390431/asset/css/default.css => generated 0 bytes in 3 msecs (HTTP/1.1 304) 3 headers in 144 bytes (0 switches on core 0)
[pid: 6518|app: 0|req: 6/5] 192.168.2.123 () {38 vars in 927 bytes} [Thu May 22 16:26:08 2014] GET /static/b73d683fe014fe015f50a47ca9390431/asset/css/icon.css => generated 0 bytes in 2 msecs (HTTP/1.1 304) 3 headers in 144 bytes (0 switches on core 2)
[pid: 6518|app: 0|req: 6/6] 192.168.2.123 () {38 vars in 931 bytes} [Thu May 22 16:26:08 2014] GET /static/b73d683fe014fe015f50a47ca9390431/asset/css/layout.css => generated 0 bytes in 5 msecs (HTTP/1.1 304) 3 headers in 144 bytes (0 switches on core 1)
[pid: 6483|app: 0|req: 2/8] 192.168.2.123 () {38 vars in 955 bytes} [Thu May 22 16:26:08 2014] GET /static/b73d683fe014fe015f50a47ca9390431/amd/dijit/themes/claro/claro.css => generated 0 bytes in 14 msecs (HTTP/1.1 304) 3 headers in 144 bytes (0 switches on core 0)
[pid: 6483|app: 0|req: 2/8] 192.168.2.123 () {38 vars in 908 bytes} [Thu May 22 16:26:08 2014] GET /static/b73d683fe014fe015f50a47ca9390431/amd/dojo/dojo.js => generated 0 bytes in 13 msecs (HTTP/1.1 304) 3 headers in 144 bytes (0 switches on core 2)
[pid: 6518|app: 0|req: 7/9] 192.168.2.123 () {34 vars in 780 bytes} [Thu May 22 16:26:09 2014] GET /resource/3 => generated 12463 bytes in 26 msecs (HTTP/1.1 200) 2 headers in 82 bytes (2 switches on core 3)
[pid: 6518|app: 0|req: 9/10] 192.168.2.123 () {38 vars in 933 bytes} [Thu May 22 16:26:09 2014] GET /static/b73d683fe014fe015f50a47ca9390431/asset/css/default.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 144 bytes (0 switches on core 0)
[pid: 6483|app: 0|req: 3/11] 192.168.2.123 () {38 vars in 931 bytes} [Thu May 22 16:26:09 2014] GET /static/b73d683fe014fe015f50a47ca9390431/asset/css/layout.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 144 bytes (0 switches on core 1)
[pid: 6518|app: 0|req: 11/12] 192.168.2.123 () {38 vars in 927 bytes} [Thu May 22 16:26:09 2014] GET /static/b73d683fe014fe015f50a47ca9390431/asset/css/icon.css => generated 0 bytes in 13 msecs (HTTP/1.1 304) 3 headers in 144 bytes (0 switches on core 2)
[pid: 6518|app: 0|req: 11/14] 192.168.2.123 () {38 vars in 955 bytes} [Thu May 22 16:26:09 2014] GET /static/b73d683fe014fe015f50a47ca9390431/amd/dijit/themes/claro/claro.css => generated 0 bytes in 14 msecs (HTTP/1.1 304) 3 headers in 144 bytes (0 switches on core 1)
[pid: 6518|app: 0|req: 11/14] 192.168.2.123 () {38 vars in 908 bytes} [Thu May 22 16:26:09 2014] GET /static/b73d683fe014fe015f50a47ca9390431/amd/dojo/dojo.js => generated 0 bytes in 13 msecs (HTTP/1.1 304) 3 headers in 144 bytes (0 switches on core 3)
Traceback (most recent call last):
  File "/home/zadmin/ngw/nextgisweb/nextgisweb/uwsgiapp.py", line 12, in application
    return app(environ, start_response)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 82, in tm_tween
    reraise(*exc_info)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 63, in tm_tween
    response = handler(request)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 118, in handle_request
    root = root_factory(request)
  File "/home/zadmin/ngw/nextgisweb/nextgisweb/resource/view.py", line 39, in resource_factory
    base = Resource.filter_by(id=request.matchdict['id']).one()
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2323, in one
    ret = list(self)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2366, in __iter__
    return self._execute_and_instances(context)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2381, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (DatabaseError) SSL error: decryption failed or bad record mac
 'SELECT resource.id AS resource_id, resource.cls AS resource_cls, resource.parent_id AS resource_parent_id, resource.keyname AS resource_keyname, resource.display_name AS resource_display_name, resource.owner_user_id AS resource_owner_user_id, resource.description AS resource_description \nFROM resource \nWHERE resource.id = %(id_1)s' {'id_1': u'3'}
[pid: 6483|app: 0|req: 4/15] 192.168.2.123 () {34 vars in 780 bytes} [Thu May 22 16:26:09 2014] GET /resource/3 => generated 0 bytes in 20 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 3)
```

**Comment by drnextgis** [comment]
`lazy` - устаревшая опция, нужно использовать `llazy-apps = true`, причём как я понял лучше всегда выставлять эту опцию, когда деплоим приложение, использующее SQLAlchemy, [подробнее](http://lists.unbit.it/pipermail/uwsgi/2011-May/002079.html). Столкнулся с чем-то похожим в CKAN-e (Pylons, SQLAlchemy), правда там другой текст ошибки.
