### ISSUE TITLE
WMS сервисы не подключаются в ArcGIS

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#337]
ArcGIS поддерживает различные способы аутентификации, в отличие от QGIS (только basic), поэтому для того, чтобы определиться какие запросы он должен отсылать серверу, ему надо как-то сообщить о типе аутентификации. Сейчас при попытке открыть GetCapabilities он попадает [сюда](https://github.com/nextgis/nextgisweb/blob/2/nextgisweb/auth/views.py#L54), а вместо этого должен приходить в ответ `HTTP 401 Not Authorized` с заголовком:
```
WWW-Authenticate: Basic realm="NextGISWeb"
```

**Comment by BishopGIS** [comment]
В идеале сделать такую штуку только для сервисов, хотя можно и для любой страницы админки: при таком ответе браузер открывает свое окно ввода пароля и логина.

**Comment by dezhin** [comment]
Я поправил это в 4e4025daf3347042887a9946a9aa4cc7d93a95c8. Вначале я думал сделать у route специальный признак, который отвечает какой способ аутентификации предпочтительней через route predicate.

Но в последний момент меня посетила мысль, что можно сделать проще - HTTP аутентификация предпочтительней в API, а в веб-интерфейсе предпочтительней обычный вход через веб-форму.

Весь API у нас в `/api/` (перенесено не все, но тем не менее), так что отличить можно по префиксу в URL. Так я и реализовал все это. В принципе есть ситуации, когда это работать будет не очень клево - логин пароль может в веб-интерфейсе вылезти, но я не думаю что мы на это наткнемся.

@KolesovDmitry, для WFS нужно перенести его с URL /resource/{id}/wfs на /api/resource/{id}/wfs. Во втором бранче я это сделал в 8386a65faa46f166b4fd043ae9688c682d68bc1b, но похоже там сервис WFS сломан и не от этого исправления.

@BishopGIS, идея использовать HTTP аутентификацию в веб-интерфейсе не очень хорошая. Там масса проблем, начиная от того, что не понятно как logout делать.

**Comment by KolesovDmitry** [comment]
@dezhin а что ты имел в виду, когда писал "там сервис WFS сломан"? Проверил вторую ветку -- вроде все на месте и работает...

**Comment by dezhin** [comment]
Мне вот такое говорит: UnboundLocalError: local variable 'datasource' referenced before assignment
Но может я как-то не так как надо его настроил. Не суть в общем.

**Comment by KolesovDmitry** [comment]
А можешь прислать stack-trace?

**Comment by dezhin** [comment]
```
Traceback (most recent call last):
  File "/home/jean/gis/ngw/env/local/lib/python2.7/site-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/home/jean/gis/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/home/jean/gis/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/jean/gis/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/jean/gis/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/home/jean/gis/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/jean/gis/ngw/nextgisweb/nextgisweb/resource/api.py", line 204, in resource_exception_tween
    response = handler(request)
  File "/home/jean/gis/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 82, in tm_tween
    reraise(*exc_info)
  File "/home/jean/gis/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 63, in tm_tween
    response = handler(request)
  File "/home/jean/gis/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/jean/gis/ngw/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/jean/gis/ngw/nextgisweb/nextgisweb/wfsserver/view.py", line 77, in handler
    request_method=request_method)
  File "/home/jean/gis/ngw/nextgisweb/nextgisweb/wfsserver/third_party/FeatureServer/Server.py", line 121, in dispatchRequest
    datasource.rollback()
```

**Comment by drnextgis** [comment]
WMS-сервис вида `http://demo.nextgis.ru/ngw/api/resource/83/wms` не открывается в ArcGIS, в то время как `http://demo.nextgis.ru:6545/api/resource/83/wms` открывается нормально.

**Comment by drnextgis** [comment]
https://github.com/nextgis/nextgisweb/commit/67cc97ed85fbdf2231e9b580188a8b4736f3a7e6
