### ISSUE TITLE
Ошибка открытия свойства ресурса

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#348]
Какой то из комитов после cf7b7fa8c76c895c242bde259551c3da63d6a2ec (на нем еще работало) ломает форму свойств ресурса ( /resource/155/update ).
При открытии пустое окно, без вкладок и тд.

**Comment by dezhin** [comment]
Наверное нужно больше деталей, в целом у меня редактирование ресурса работает после указанного коммита.

**Comment by yellow-sky** [comment]
У меня вылетает такой экс:
```
ERROR:waitress:Exception when serving /resource/widget
Traceback (most recent call last):
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/yellow/GIT_NEXTGIS/nextgisweb/nextgisweb/resource/api.py", line 207, in resource_exception_tween
    response = handler(request)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 99, in tm_tween
    reraise(*exc_info)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 80, in tm_tween
    response = handler(request)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/home/yellow/GIT_NEXTGIS/nextgisweb/nextgisweb/pyramidcomp.py", line 32, in wrapped
    return f(request, *args, **kwargs)
  File "/home/yellow/GIT_NEXTGIS/nextgisweb/nextgisweb/resource/view.py", line 179, in widget
    .filter_by(id=resid).one()
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2323, in one
    ret = list(self)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2366, in __iter__
    return self._execute_and_instances(context)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2381, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/home/yellow/Project/Compulink/test_env/env/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) column wmsclient_connection.username does not exist
LINE 1: ...nnection.version AS wmsclient_connection_version, wmsclient_...
                                                             ^
 'SELECT resource.id AS resource_id, resource.cls AS resource_cls, resource.parent_id AS resource_parent_id, resource.keyname AS resource_keyname, resource.display_name AS resource_display_name, resource.owner_user_id AS resource_owner_user_id, resource.description AS resource_description, resource_group.id AS resource_group_id, vector_layer.id AS vector_layer_id, vector_layer.tbl_uuid AS vector_layer_tbl_uuid, vector_layer.geometry_type AS vector_layer_geometry_type, vector_layer.srs_id AS vector_layer_srs_id, vector_layer.feature_label_field_id AS vector_layer_feature_label_field_id, webmap.id AS webmap_id, webmap.root_item_id AS webmap_root_item_id, webmap.bookmark_resource_id AS webmap_bookmark_resource_id, webmap.extent_left AS webmap_extent_left, webmap.extent_right AS webmap_extent_right, webmap.extent_bottom AS webmap_extent_bottom, webmap.extent_top AS webmap_extent_top, wfsserver_service.id AS wfsserver_service_id, file_bucket.id AS file_bucket_id, file_bucket.stuuid AS file_bucket_stuuid, file_bucket.tstamp AS file_bucket_tstamp, mapserver_style.id AS mapserver_style_id, mapserver_style.xml AS mapserver_style_xml, lookup_table.id AS lookup_table_id, lookup_table.val AS lookup_table_val, raster_style.id AS raster_style_id, wmsserver_service.id AS wmsserver_service_id, raster_layer.id AS raster_layer_id, raster_layer.fileobj_id AS raster_layer_fileobj_id, raster_layer.xsize AS raster_layer_xsize, raster_layer.ysize AS raster_layer_ysize, raster_layer.band_count AS raster_layer_band_count, raster_layer.srs_id AS raster_layer_srs_id, postgis_connection.id AS postgis_connection_id, postgis_connection.hostname AS postgis_connection_hostname, postgis_connection.database AS postgis_connection_database, postgis_connection.username AS postgis_connection_username, postgis_connection.password AS postgis_connection_password, postgis_layer.id AS postgis_layer_id, postgis_layer.connection_id AS postgis_layer_connection_id, postgis_layer.schema AS postgis_layer_schema, postgis_layer."table" AS postgis_layer_table, postgis_layer.column_id AS postgis_layer_column_id, postgis_layer.column_geom AS postgis_layer_column_geom, postgis_layer.geometry_type AS postgis_layer_geometry_type, postgis_layer.geometry_srid AS postgis_layer_geometry_srid, postgis_layer.srs_id AS postgis_layer_srs_id, postgis_layer.feature_label_field_id AS postgis_layer_feature_label_field_id, wmsclient_connection.id AS wmsclient_connection_id, wmsclient_connection.url AS wmsclient_connection_url, wmsclient_connection.version AS wmsclient_connection_version, wmsclient_connection.username AS wmsclient_connection_username, wmsclient_connection.password AS wmsclient_connection_password, wmsclient_connection.capcache_xml AS wmsclient_connection_capcache_xml, wmsclient_connection.capcache_json AS wmsclient_connection_capcache_json, wmsclient_connection.capcache_tstamp AS wmsclient_connection_capcache_tstamp, wmsclient_layer.id AS wmsclient_layer_id, wmsclient_layer.connection_id AS wmsclient_layer_connection_id, wmsclient_layer.wmslayers AS wmsclient_layer_wmslayers, wmsclient_layer.imgformat AS wmsclient_layer_imgformat, wmsclient_layer.srs_id AS wmsclient_layer_srs_id, focl_project.id AS focl_project_id, focl_struct.id AS focl_struct_id, focl_struct.region AS focl_struct_region, focl_struct.district AS focl_struct_district, focl_struct.external_id AS focl_struct_external_id, focl_struct.status AS focl_struct_status, focl_struct.status_upd_user AS focl_struct_status_upd_user, focl_struct.status_upd_dt AS focl_struct_status_upd_dt, situation_plan.id AS situation_plan_id, situation_plan.region AS situation_plan_region, situation_plan.district AS situation_plan_district \nFROM resource LEFT OUTER JOIN resource_group ON resource_group.id = resource.id LEFT OUTER JOIN vector_layer ON vector_layer.id = resource.id LEFT OUTER JOIN webmap ON webmap.id = resource.id LEFT OUTER JOIN wfsserver_service ON wfsserver_service.id = resource.id LEFT OUTER JOIN file_bucket ON file_bucket.id = resource.id LEFT OUTER JOIN mapserver_style ON mapserver_style.id = resource.id LEFT OUTER JOIN lookup_table ON lookup_table.id = resource.id LEFT OUTER JOIN raster_style ON raster_style.id = resource.id LEFT OUTER JOIN wmsserver_service ON wmsserver_service.id = resource.id LEFT OUTER JOIN raster_layer ON raster_layer.id = resource.id LEFT OUTER JOIN postgis_connection ON postgis_connection.id = resource.id LEFT OUTER JOIN postgis_layer ON postgis_layer.id = resource.id LEFT OUTER JOIN wmsclient_connection ON wmsclient_connection.id = resource.id LEFT OUTER JOIN wmsclient_layer ON wmsclient_layer.id = resource.id LEFT OUTER JOIN focl_project ON focl_project.id = resource.id LEFT OUTER JOIN focl_struct ON focl_struct.id = resource.id LEFT OUTER JOIN situation_plan ON situation_plan.id = resource.id \nWHERE resource.id = %(id_1)s' {'id_1': u'823'}
```

Может что-то поменялось в БД? Следом за этим коммитом идут коммиты с новой функциональностью по WMS вроде.

**Comment by dezhin** [comment]
Нужно что написано вот тут сделать - https://github.com/nextgis/nextgisweb/pull/338
