### ISSUE TITLE
Проблема запуска_nextgisweb

### ISSUE THREAD

**Issue by paleogis** [nextgis/nextgisweb#357]
Поставил некстгисвеб согласно инструкции на убунту 12.04  запустил старт сервера
user@user:~/ngw$ env/bin/pserve development.ini, сам файл создал по шаблону в котором ничего не менял.
В итоге терминал  пишет 
" File "/home/user/ngw/nextgisweb/nextgisweb/pyramidcomp.py", line 233, in make_app
    assert 'secret' in settings, 'Secret not set!'
AssertionError: Secret not set!"
Закомитил эту строчку и снова запустил команду 
"user@user:~/ngw$ env/bin/pserve development.ini
Starting server in PID 4248.
serving on http://0.0.0.0:6543"
Терминал пишет все ок, перехожу по адресу  http://0.0.0.0:6543
нехствебгис не запустился 
  "  Connection to 0.0.0.0 failed.
The system returned: (111) Connection refused"
На запрос http://localhost:6543/, пишет Internal Server Error
The server encountered an unexpected internal server error

(generated by waitress)
Терминал 
AttributeError: 'thread._local' object has no attribute 'indentation'
Logged from file channel.py, line 340
Вопрос, как правильно запустить некстгисвеб, подскажите чайнику:)
Может чего упустил?
Лог Терминала
user@user:~$ cd ngw
user@user:~/ngw$ env/bin/pserve development.ini
Traceback (most recent call last):
  File "env/bin/pserve", line 11, in <module>
    sys.exit(main())
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 328, in run
    global_conf=vars)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 363, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/user/ngw/nextgisweb/nextgisweb/__init__.py", line 69, in main
    config = env.pyramid.make_app(settings)
  File "/home/user/ngw/nextgisweb/nextgisweb/pyramidcomp.py", line 233, in make_app
    assert 'secret' in settings, 'Secret not set!'
AssertionError: Secret not set!
user@user:~/ngw$ env/bin/pserve development.ini
Starting server in PID 4248.
serving on http://0.0.0.0:6543
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 846, in emit
    msg = self.format(record)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pip/utils/logging.py", line 106, in format
    msg = logging.StreamHandler.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 723, in format
    return fmt.format(record)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pip/utils/logging.py", line 55, in format
    for line in formatted.splitlines(True)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pip/utils/logging.py", line 42, in get_indentation
    return _log_state.indentation
AttributeError: 'thread._local' object has no attribute 'indentation'
Logged from file channel.py, line 340

**Comment by BishopGIS** [comment]
В конфиге все поля что отмечены 
```
(Обязательно)
```
должны быть раскоментированы и заполнены.

В данном случае видимо не установлено
# Ключ, используемый для шифрования cookies (обязательно)
secret =

```
Для генерации ключа для конфигурационного файла config.ini можно воспользоваться командой

openssl rand -base64 16
```

**Comment by paleogis** [comment]
Спасибо, Дмитрий! Но пока я своими кривыми руками не могу запустить, в терминале пишет  user@user:~/ngw$ env/bin/pserve development.ini
Starting server in PID 3416.
serving on http://0.0.0.0:6543 
однако сервис в браузере не запускается
вот конфиг 
[file_upload]

# Директория для временного хранения загруженных файлов (обязательно) 
path = /home/user/ngw/temp 

[pyramid]

# Ключ, используемый для шифрования cookies (обязательно) 
secret = 2lTusLQvw86tcFRAXRh4qw==
# HTML-справка 
# help_page = 
# Логотип системы 
# logo = 
# Значок для избранного 
# favicon = 
# Ссылка для редиректа, при заходе на / 
# home_url = 

[core]

# Название системы 
system.name = NextGIS Web
# Полное название системы 
system.full_name = Геоинформационная система NextGIS
# Имя сервера БД 
database.host = localhost
# Имя БД на сервере 
database.name = nextgisweb
# Имя пользователя БД 
database.user = nextgisweb
# Пароль пользователя БД 
# database.password = 
# Проверять подключение при запуске 
# database.check_at_startup = 
# Не загружать перечисленные пакеты 
# packages.ignore = 
# Не загружать перечисленные компоненты 
# components.ignore = 
# Директория для хранения данных 
# sdir = 

[file_storage]

# Директория для хранения файлов (обязательно) 
path = /home/user/ngw/data

[feature_layer]

# Показывать атрибуты в идентификации 
# identify.attributes = 

[webmap]

# Файл с описанием базовых слоёв 
# basemaps = 
# Bing Maps API-ключ 
# bing_apikey = 
# Чувствительность идентификации (3px) 
# identify_radius = 
# Ширина всплывающего окна 
# popup_width = 
# Высота всплывающего окна 
# popup_height = 

[wmsclient]


[mapserver]

# Список шрифтов в формате MAPFILE FONTSET 
# fontset =

**Comment by BishopGIS** [comment]
А то что комментировал вернул обратно?
Фаервол ничего не блокирует?
Какой адрес в браузере (IP должен совпадать с ssh)?

**Comment by paleogis** [comment]
А то что комментировал вернул обратно?
Да
Фаервол ничего не блокирует?
У меня его нет, апач на localhost отвечает It works!
Какой адрес в браузере (IP должен совпадать с ssh)?
На  http://localhost:6543/,   http://192.168.8.132:6543/, отвечает
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
Насчет "IP должен совпадать с ssh", с этого места поподробнее?

**Comment by BishopGIS** [comment]
Да, все верно. После того как браузер написал 
```
Internal Server Error

The server encountered an unexpected internal server error
```

Что валится в консоль?

И еще в конфиге вот этот параметр тоже вот так прописать
sdir = /home/user/ngw/data

**Comment by paleogis** [comment]
Спасибо конфиг поправлю
Терминал выдает следующее
user@user:~/ngw$ env/bin/pserve development.ini
Starting server in PID 3102.
serving on http://0.0.0.0:6543
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 846, in emit
    msg = self.format(record)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pip/utils/logging.py", line 106, in format
    msg = logging.StreamHandler.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 723, in format
    return fmt.format(record)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pip/utils/logging.py", line 55, in format
    for line in formatted.splitlines(True)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pip/utils/logging.py", line 42, in get_indentation
    return _log_state.indentation
AttributeError: 'thread._local' object has no attribute 'indentation'
Logged from file channel.py, line 340
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 846, in emit
    msg = self.format(record)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pip/utils/logging.py", line 106, in format
    msg = logging.StreamHandler.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 723, in format
    return fmt.format(record)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pip/utils/logging.py", line 55, in format
    for line in formatted.splitlines(True)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pip/utils/logging.py", line 42, in get_indentation
    return _log_state.indentation
AttributeError: 'thread._local' object has no attribute 'indentation'
Logged from file channel.py, line 340

**Comment by paleogis** [comment]
После подключения sdir = /home/user/ngw/data
В терминале вываливает ошибку 
user@user:~/ngw$ env/bin/pserve development.ini
Starting server in PID 3757.
Traceback (most recent call last):
  File "env/bin/pserve", line 11, in <module>
    sys.exit(main())
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 360, in run
    serve()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 339, in serve
    server(app)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 189, in server_wrapper
    **context.local_conf)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/waitress/__init__.py", line 21, in serve_paste
    serve(app, **kw)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/waitress/__init__.py", line 11, in serve
    server = _server(app, **kw)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/waitress/server.py", line 44, in create_server
    return cls(application, map, _start, _sock, _dispatcher, adj)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/waitress/server.py", line 76, in __init__
    self.bind_server_socket()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/waitress/server.py", line 184, in bind_server_socket
    self.bind((self.adj.host, self.adj.port))
  File "/usr/lib/python2.7/asyncore.py", line 341, in bind
    return self.socket.bind(addr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
user@user:~/ngw$

**Comment by drnextgis** [comment]
1. Последняя ошибка свидетельствует о том, что уже что-то запущено на этом порту
2. Для решения вот этого:

    ```
    AttributeError: 'thread._local' object has no attribute 'indentation'
    ```

  Попробую продаунгрейдить `pip`:

      pip install pip==1.5.4

**Comment by paleogis** [comment]
Привет, Дмитрий! Спасибо за подсказку, ввел команду в терминал pip install pip==1.5.4  и получил ошибку 
user@user:~$ pip install pip==1.5.4
Downloading/unpacking pip==1.5.4
  Downloading pip-1.5.4.tar.gz (1.1Mb): 1.1Mb downloaded
  Running setup.py egg_info for package pip
    
    warning: no files found matching 'pip/cacert.pem'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no previously-included files matching '*.rst' found under directory 'docs/_build'
    no previously-included directories found matching 'docs/_build/_sources'
Installing collected packages: pip
  Found existing installation: pip 1.0
    Uninstalling pip:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 228, in run
    requirement_set.install(install_options, global_options)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1089, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 476, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1391, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 248, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 300, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/bin/pip'

Storing complete log in /home/user/.pip/pip.log
user@user:~$

**Comment by drnextgis** [comment]
Это надо делать в виртуальном окружении, то есть если оно не активировано, то вызывать так:

````
env/bin/pip install pip==1.5.4 
```

**Comment by paleogis** [comment]
Спасибо, вроде поставил user@user:~/ngw$ env/bin/pip install pip==1.5.4 
Collecting pip==1.5.4
/home/user/ngw/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading pip-1.5.4-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 236kB/s 
Installing collected packages: pip
  Found existing installation: pip 7.1.0
    Uninstalling pip-7.1.0:
      Successfully uninstalled pip-7.1.0
Successfully installed pip-1.5.4

**Comment by drnextgis** [comment]
Хорошо, проблема решена или ngw так и не удалось запустить?

**Comment by paleogis** [comment]
К сожалению нгв так и не удалось запустить, как можно диагностировать возможную ошибку?

**Comment by drnextgis** [comment]
А что пишет в консоли при запуске?

**Comment by paleogis** [comment]
user@user:~$ cd ngw
user@user:~/ngw$ env/bin/pserve development.ini
Starting server in PID 2924.
serving on http://0.0.0.0:6543

**Comment by paleogis** [comment]
Если запустить http://localhost:6543/, то терминал вываливает ERROR:waitress:Exception when serving /resource/0
Traceback (most recent call last):
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/user/ngw/nextgisweb/nextgisweb/resource/api.py", line 207, in resource_exception_tween
    response = handler(request)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 99, in tm_tween
    reraise(*exc_info)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 80, in tm_tween
    response = handler(request)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 118, in handle_request
    root = root_factory(request)
  File "/home/user/ngw/nextgisweb/nextgisweb/resource/view.py", line 38, in resource_factory
    base = Resource.filter_by(id=request.matchdict['id']).one()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2323, in one
    ret = list(self)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2366, in __iter__
    return self._execute_and_instances(context)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2379, in _execute_and_instances
    close_with_result=True)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2370, in _connection_from_session
    **kw)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 802, in connection
    close_with_result=close_with_result)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 806, in _connection_for_bind
    return self.transaction._connection_for_bind(engine)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 299, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1661, in contextual_connect
    self.pool.connect(),
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 326, in connect
    return _ConnectionFairy(self).checkout()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 485, in __init__
    rec = self._connection_record = pool._do_get()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 770, in _do_get
    return self._create_connection()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 279, in _create_connection
    return _ConnectionRecord(self)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 372, in __init__
    self.connection = self.__connect()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 433, in __connect
    connection = self.__pool._creator()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 283, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: (OperationalError) fe_sendauth: no password supplied
 None None

**Comment by drnextgis** [comment]
ngw не может подключиться к БД, правильно ли указаны реквизиты доступа к БД в файле `config.ini`?

**Comment by paleogis** [comment]
Вроде все стоит по умолчанию
[core]

# Название системы
system.name = NextGIS Web
# Полное название системы
system.full_name = Геоинформационная система NextGIS
# Имя сервера БД
database.host = localhost
# Имя БД на сервере
database.name = nextgisweb
# Имя пользователя БД
database.user = nextgisweb
# Пароль пользователя БД
# database.password =
# Проверять подключение при запуске
# database.check_at_startup =
# Не загружать перечисленные пакеты
# packages.ignore =
# Не загружать перечисленные компоненты
# components.ignore =
# Директория для хранения данных
sdir = /home/user/ngw/data

С уважением, Лаврентьев Никита




10 августа 2015 г., 11:44 пользователь Denis Rykov <notifications@github.com

**Comment by drnextgis** [comment]
В этом и проблема. Всё же описано в документации. Прежде чем запускать ngw, нужно создать БД PostGIS (про это  [тут](http://docs.nextgis.ru/docs_ngweb/source/install.html#id2)) и инициализировать её ([тут](http://docs.nextgis.ru/docs_ngweb/source/install.html#id9)).

**Comment by paleogis** [comment]
Спасибо, вроде БД PostGIS  Создал, но config  не менял, попробую исправить

**Comment by paleogis** [comment]
Денис, подскажи чайнику, что нужно прописывать в listen_adress="*" ?
user@user:~$ sudo service postgresql restart
[sudo] password for user:
 * Restarting PostgreSQL 9.1 database server
      * Error: Invalid line 557 in
/etc/postgresql/9.1/main/postgresql.conf: »listen_adress="*"
«

 [fail]
user@user:~$ sudo service postgresql restart
 * Restarting PostgreSQL 9.1 database server
      * Error: Invalid line 557 in
/etc/postgresql/9.1/main/postgresql.conf: »listen_adress="0.0.0.0"
«

 [fail]
user@user:~$


С уважением, Лаврентьев Никита




10 августа 2015 г., 12:04 пользователь Denis Rykov <notifications@github.com

**Comment by drnextgis** [comment]
Прослушиваемый адрес, например, `127.0.0.1` для локалхоста, а `*` - для любого, то есть скорее всего тебе в строке `listen_adress="*"` ничего трогать не нужно.

**Comment by paleogis** [comment]
Ок, Денис. А что нужно сделать чтобы не получать ошибку
* Restarting PostgreSQL 9.1 database server
    * Error: Invalid line 557 in /etc/postgresql/9.1/main/postgresql.conf:
»listen_adress="*"
«

 [fail]

С уважением, Лаврентьев Никита




10 августа 2015 г., 13:17 пользователь Denis Rykov <notifications@github.com

**Comment by drnextgis** [comment]
Заменить двойные кавычки на одинарные.

**Comment by paleogis** [comment]
Спасибо, кавычки заменил на listen_adress='*', однако снова ругается
user@user:~$ sudo service postgresql restart
 * Restarting PostgreSQL 9.1 database server
      * The PostgreSQL server failed to start. Please check the log output:
FATAL:  unrecognized configuration parameter "listen_adress"

 [fail]


С уважением, Лаврентьев Никита




2015-08-10 13:34 GMT+03:00 Denis Rykov <notifications@github.com>:

**Comment by drnextgis** [comment]
Этот параметр правильно пишется как `listen_addresses`.

**Comment by paleogis** [comment]
Спасибо, Денис! Вам нужно будет поправить в руководстве пользователя этот
момент,
пока там написано

nano /etc/postgresql/9.3/main/postgresql.conf
делаем строку listen_adress="*", и расскоментируем её.


С уважением, Лаврентьев Никита




2015-08-10 13:42 GMT+03:00 Denis Rykov <notifications@github.com>:

**Comment by paleogis** [comment]
После того как добавил  в  /etc/postgresql/9.3/main/pg_hba.conf

делаем строку host    all     all     md5

Терминал пишет ошибку user@user:~$ sudo service postgresql restart
 * Restarting PostgreSQL 9.1 database server
          * The PostgreSQL server failed to start. Please check the
log output:
2015-08-10 12:52:15 MSK LOG:  end-of-line before authentication method
2015-08-10 12:52:15 MSK CONTEXT:  line 100 of configuration file
"/etc/postgresql/9.1/main/pg_hba.conf"
2015-08-10 12:52:15 MSK FATAL:  could not load pg_hba.conf
                                                                         [fail]



С уважением, Лаврентьев Никита




10 августа 2015 г., 13:55 пользователь Nikita Lavrentiev <lvnikita@gmail.com

**Comment by drnextgis** [comment]
```
host    all             all             127.0.0.1/32            md5
```

**Comment by paleogis** [comment]
Спасибо, работает будет двигаться дальше
user@user:~$ sudo service postgresql restart
[sudo] password for user:
 * Restarting PostgreSQL 9.1 database server                             [
OK ]
user@user:~$


С уважением, Лаврентьев Никита




2015-08-10 14:21 GMT+03:00 Denis Rykov <notifications@github.com>:

**Comment by paleogis** [comment]
Спасибо всем, ngw запустил.

С уважением, Лаврентьев Никита




2015-08-10 14:51 GMT+03:00 Nikita Lavrentiev <lvnikita@gmail.com>:

**Comment by drnextgis** [comment]
Тогда закрываю. Проблемные места в документации поправил.
