### ISSUE TITLE
Не учитывается featurePrefix при запросе данных WFS

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#398]
Если посмотреть на фрагмент данных, возвращаемых нашим WFS:

```xml
<gml:featureMember gml:id="1"><fs:boundary-polygon fid="1">...
```

то можно увидеть, что слой имеет префикс `fs`, но почему тогда при попытке запросить данные с указанием этого префикса ничего не выходит? Пример запроса:

```xml
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/WFS-transaction.xsd">
<wfs:Query typeName="fs:boundary-polygon"/>
</wfs:GetFeature>
```

Ответ:

```
Can't find layer 'fs:boundary-polygon'
```

**Comment by dezhin** [comment]
А в запросе указать соответствующий xmlns пробовали?

**Comment by drnextgis** [comment]
Пробовали, всё равно не работает.
10.10.2015 23:34 пользователь "Aleksandr Dezhin" <notifications@github.com>
написал:

**Comment by KolesovDmitry** [comment]
@drnextgis, теперь должно работать

**Comment by drnextgis** [comment]
Вообще перестало работать:

```
ERROR:waitress:Exception when serving /api/resource/69/wfs
Traceback (most recent call last):
  File "/usr/home/dezhin/ngw/env/lib/python2.7/site-packages/waitress/channel.py", line 329, in service
    task.service()
  File "/usr/home/dezhin/ngw/env/lib/python2.7/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/usr/home/dezhin/ngw/env/lib/python2.7/site-packages/waitress/task.py", line 380, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/home/dezhin/ngw/env/lib/python2.7/site-packages/pyramid/router.py", line 223, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/home/dezhin/ngw/env/lib/python2.7/site-packages/pyramid/router.py", line 198, in invoke_subrequest
    response = handle_request(request)
  File "/usr/home/dezhin/ngw/env/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/usr/home/dezhin/ngw/nextgisweb/nextgisweb/resource/api.py", line 204, in resource_exception_tween
    response = handler(request)
  File "/usr/home/dezhin/ngw/env/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 82, in tm_tween
    reraise(*exc_info)
  File "/usr/home/dezhin/ngw/env/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 63, in tm_tween
    response = handler(request)
  File "/usr/home/dezhin/ngw/env/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/usr/home/dezhin/ngw/env/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/usr/home/dezhin/ngw/env/lib/python2.7/site-packages/pyramid/config/views.py", line 384, in viewresult_to_response
    result = view(context, request)
  File "/usr/home/dezhin/ngw/nextgisweb/nextgisweb/wfsserver/view.py", line 81, in handler
    request_method=request_method)
  File "/usr/home/dezhin/ngw/nextgisweb/nextgisweb/wfsserver/third_party/FeatureServer/Server.py", line 115, in dispatchRequest
    name = action.layer[len(p):]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by drnextgis** [comment]
@KolesovDmitry, я вроде поправил ошибку, посмотри. Если всё хорошо, то можно закрыть, проверил - в OpenLayers 2.13.1 работает.

**Comment by KolesovDmitry** [comment]
@drnextgis, спасибо за фикс, теперь все работает.
