### ISSUE TITLE
WFS. Указание параметра bbox приводит к ошибке.

### ISSUE THREAD

**Issue by alisovenko** [nextgis/nextgisweb#457]
Создал в ngw wfs service.
Создал подключение к сервису в qgis.
При добавлении слоя в qgis если стоит галка "Only request features overlapping the current view extent" слой не грузится, qgis пишет ошибку.

Если пробовать запрос через браузер, то получаю 502.
Если из запроса убираю параметр BBOX, то запрос успешно выполняется.

**Comment by KolesovDmitry** [comment]
Подтверждаю. В консоль при этом вываливается ошибка:
```
Exception when serving /api/resource/16/wfs
Traceback (most recent call last):
  File "/home/dima/laboro/NextGIS/NGW/env/local/lib/python2.7/site-packages/waitress/channel.py", line 336, in service
    task.service()
  File "/home/dima/laboro/NextGIS/NGW/env/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/dima/laboro/NextGIS/NGW/env/local/lib/python2.7/site-packages/waitress/task.py", line 388, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/dima/laboro/NextGIS/NGW/env/local/lib/python2.7/site-packages/pyramid/router.py", line 223, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/dima/laboro/NextGIS/NGW/env/local/lib/python2.7/site-packages/pyramid/router.py", line 198, in invoke_subrequest
    response = handle_request(request)
  File "/home/dima/laboro/NextGIS/NGW/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/dima/laboro/NextGIS/NGW/nextgisweb/nextgisweb/resource/api.py", line 204, in resource_exception_tween
    response = handler(request)
  File "/home/dima/laboro/NextGIS/NGW/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/dima/laboro/NextGIS/NGW/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/dima/laboro/NextGIS/NGW/env/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/home/dima/laboro/NextGIS/NGW/env/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/home/dima/laboro/NextGIS/NGW/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/dima/laboro/NextGIS/NGW/nextgisweb/nextgisweb/wfsserver/view.py", line 86, in handler
    request_method=request_method)
  File "/home/dima/laboro/NextGIS/NGW/nextgisweb/nextgisweb/wfsserver/third_party/FeatureServer/Server.py", line 85, in dispatchRequest
    request.parse(params, path_info, host, post_data, request_method)
  File "/home/dima/laboro/NextGIS/NGW/nextgisweb/nextgisweb/wfsserver/third_party/FeatureServer/Service/WFS.py", line 64, in parse
    format_obj=wfsrequest)
  File "/home/dima/laboro/NextGIS/NGW/nextgisweb/nextgisweb/wfsserver/third_party/FeatureServer/Service/Request.py", line 74, in parse
    action = self.get_select_action(path_info, params)
  File "/home/dima/laboro/NextGIS/NGW/nextgisweb/nextgisweb/wfsserver/third_party/FeatureServer/Service/Request.py", line 212, in get_select_action
    action = self._set_bbox(action, value)
  File "/home/dima/laboro/NextGIS/NGW/nextgisweb/nextgisweb/wfsserver/third_party/FeatureServer/Service/Request.py", line 113, in _set_bbox
    coords = bbox_value['coords']
TypeError: string indices must be integers
```
