### ISSUE TITLE
Некорректное поведение при смене родителя

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#488]
1. создать групповой ресурс
2. войти в свойства
3. сменить Родителя на любую веб-карту (можно основную)
4. нажать Сохранить

Ожидается - Окно с сообщением об ошибке, что смена родителя невозможно

Имеется - С виду успешное сохранение. Хотя фактического сохранения не происходит. В консоли браузера:
```
TypeError: Cannot read property 'message' of undefined TypeError: Cannot read property 'message' of undefined at errorMessage (/static/ddd259959968c217259793203275389b/amd/ngw-resource/CompositeWidget.js:325:126) at unlock (/static/ddd259959968c217259793203275389b/amd/ngw-resource/CompositeWidget.js:309:43) at /static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:38902 at _2f8 (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:68328) at _2f2 (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:68192) at _2f7._310.reject (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:69903) at /static/ddd259959968c217259793203275389b/amd/ngw-resource/CompositeWidget.js:262:50 at _2f8 (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:68328) at _2f2 (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:68192) at _2f7._310.reject (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:69903) ---------------------------------------- rejected at _2fe (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:68969) at _2f8 (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:68580) at _2f2 (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:68192) at _2f7._310.reject (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:69903) at /static/ddd259959968c217259793203275389b/amd/ngw-resource/CompositeWidget.js:262:50 at _2f8 (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:68328) at _2f2 (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:68192) at _2f7._310.reject (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:69903) at /static/ddd259959968c217259793203275389b/amd/ngw-resource/CompositeWidget.js:231:26 at _2f8 (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:68328) ---------------------------------------- Error at _2f7.then._305.then (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:70141) at updateObj (/static/ddd259959968c217259793203275389b/amd/ngw-resource/CompositeWidget.js:353:16) at .onClick (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:38902) at _onClick (/static/ddd259959968c217259793203275389b/amd/dijit/form/_ButtonMixin.js:16:9) at HTMLInputElement.<anonymous> (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:38832) at __onClick (/static/ddd259959968c217259793203275389b/amd/dijit/form/_ButtonMixin.js:7:16) at HTMLSpanElement.<anonymous> (/static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8:38832)
 /static/ddd259959968c217259793203275389b/amd/dojo/dojo.js:8
```

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/9b7cb2b01cea0153913b3e77e04304c8cdcd92a0
