### ISSUE TITLE
KeyError 'sdir' on both database initialization and deletion

### ISSUE THREAD

**Issue by hridaydutta123** [nextgis/nextgisweb#559]
`Traceback (most recent call last):
  File "env/bin/nextgisweb", line 11, in <module>
    load_entry_point('nextgisweb', 'console_scripts', 'nextgisweb')()
  File "/home/pi/ngw/nextgisweb/nextgisweb/script.py", line 65, in main
    args.command.execute(args, env)
  File "/home/pi/ngw/nextgisweb/nextgisweb/core/command.py", line 36, in execute
    comp.initialize_db()
  File "/home/pi/ngw/nextgisweb/nextgisweb/file_upload/__init__.py", line 19, in initialize_db
    self.env.core.mksdir(self)
  File "/home/pi/ngw/nextgisweb/nextgisweb/core/__init__.py", line 104, in mksdir
    self.bmakedirs(self.settings['sdir'], comp.identity)
KeyError: 'sdir'`

For the step [Database Initialization](http://docs.nextgis.com/docs_ngweb/source/install-ubuntu.html#database-initialization) i am getting the above error.

**Comment by drnextgis** [comment]
Did you set `sdir` option at your configuration file like [here](http://docs.nextgis.com/docs_ngweb/source/install-ubuntu.html#example-of-nextgis-web-configuration-file).

**Comment by hridaydutta123** [comment]
@drnextgis  Thank you.. Resolved!!
