### ISSUE TITLE
Ошибка создания растрового слоя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#61]
При загрузке растрового файла иногда появляется ошибка. В консоли валит следующее: 
```python
ERROR:waitress:Exception when serving /layer/create
Traceback (most recent call last):
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 272, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 247, in invoke_subrequest
    response = handle_request(request)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 82, in tm_tween
    reraise(*exc_info)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 63, in tm_tween
    response = handler(request)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 460, in mapped_view
    return _mapped_view(context, request)
  File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/home/zadmin/ngw/nextgisweb/nextgisweb/views/model_controller.py", line 62, in create
    if widget.validate():
  File "/home/zadmin/ngw/nextgisweb/nextgisweb/object_widget.py", line 135, in validate
    result = result and s.validate()
  File "/home/zadmin/ngw/nextgisweb/nextgisweb/raster_layer/views.py", line 32, in validate
    datafile, metafile = file_upload.get_filename(self.data['file']['id'])
KeyError: 'file'
```

Слой не создается, окно не меняется. При повторном нажатии кнопки "сохранить", все загружается, ошибок нет. Есть подозрение, что нажатие на кнопку выполнено до смены надписи 100% загружено на имя загруженного файла.
Наверное, кнопка должна быть неактивна пока все условия не выполнены.

**Comment by drnextgis** [comment]
В https://github.com/nextgis/nextgisweb/commit/2c01c34a7e6465c4a94b324be107e00ba9acac1e добавил проверку на предмет того, что файл загружен, теперь пока файл не загружен, запрос не будет уходить на сервер.
