### ISSUE TITLE
running dev build get /pyramid/__init__.py", line 171, in make_app     pip.main(['freeze', ])

### ISSUE THREAD

**Issue by killertonez** [nextgis/nextgisweb#634]
while installing nextgis web i get his error when trying to start  env/bin/pserve development.ini

```
nextgisweb:~/ngw$ env/bin/pserve development.ini                           
/home/user/ngw/env/local/lib/python2.7/site- 
 packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from 
 release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For 
 details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "env/bin/pserve", line 11, in <module>
    sys.exit(main())
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 32, in >main
    return command.run()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 229, in >run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/plaster_pastedeploy/__init__.py", line >131, in get_wsgi_app
    global_conf=defaults)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in >loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in >loadobj
    return context.create()
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in >create
    return self.object_type.invoke(self)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in >invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/user/ngw/env/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/user/ngw/nextgisweb/nextgisweb/__init__.py", line 70, in main
  config = env.pyramid.make_app(settings)
  File "/home/user/ngw/nextgisweb/nextgisweb/pyramid/__init__.py", line 171, in make_app
  pip.main(['freeze', ])
AttributeError: 'module' object has no attribute 'main'
user@nextgisweb:~/ngw$ /pyramid/__init__.py", line 171, in make_app
     pip.main(['freeze
```

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/90ced4c727a9196c73ac6f5ac34be8b06cfacbb4

**Comment by killertonez** [comment]
IT Does not

**Comment by killertonez** [comment]
never mind i got it working had to set mapserver version again
